baseURL = "https://saintjosephath.github.io"
title = "Institut Saint-Joseph Ath"
publishDir = "../saintjosephath.github.io"
languageCode = "fr-be"
defaultContentLanguage = "fr"

canonifyURLs = true
buildExpired = true

disableKinds = ["RSS"]

enableRobotsTXT = true

paginate = 10
summaryLength = 64

[taxonomies]
tag = "tags"

[params]
warning = "Nouvelles mesures COVID en application Ã  partir du 01/12/2021"
facebook = "https://www.facebook.com/search/top?q=institut%20saint-joseph%20ath-maffle"
