baseURL = "http://webdev.local:8088/saintjosephath/"
title = "Institut Saint-Joseph Ath"
publishDir = "/Users/greg/Web/saintjosephath"
languageCode = "fr-be"
defaultContentLanguage = "fr"

canonifyURLs = true
buildExpired = true

disableKinds = ["RSS"]

enableRobotsTXT = true

paginate = 10
summaryLength = 64

[taxonomies]
tag = "tags"

[params]
#warning = "Reprise des repas chaud et des activités extra scolaire à partir du 07 Février 2022"
facebook = "https://www.facebook.com/Saint.Joseph.Ath.Maffle"
